In [1]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.50.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2026.2.25 in /opt/anaconda3/lib/python3.14/site-packages (from selenium) (2026.6.17)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /opt/anaconda3/lib/python3.14/site-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /opt/anaconda3/lib/python3.14/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /opt/anaconda3/lib/python3.14/site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /opt/anaconda3/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in /opt/anaconda3/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (3.18)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /opt/anaconda3/lib/python3.14/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /opt/anaconda3/lib/python3.14/site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.50.0-py3-none-any.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 33.3 MB/s  0:00:0034.9 MB/s eta 0:00:01
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, sniffio, outcome, trio, trio-websocket, selenium
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [selenium]━━ 5/6 [selenium]
Successfully installed outcome-1.3.0.post0 selenium-4.50.0 sniffio-1.3.1 trio-0.34.0 trio-websocket-0.12.2 wsproto-1.3.2

In [24]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from bs4 import BeautifulSoup

import pandas as pd
import re
import os

from datetime import datetime

In [25]:


url = "https://www.purdue.edu/recwell/facility-usage/index.php"

driver = webdriver.Chrome()

driver.get(url)

#Give the page time to load the facility data
time.sleep(5)

print(driver.page_source[:2000])

<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"><head>
<title>
Facility Usage | Purdue University
</title>
<link href="https://www.purdue.edu/recwell/facility-usage/index.php" rel="canonical">

<meta charset="utf-8">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta content="width=device-width,initial-scale=1" name="viewport">

 <!-- Google tag (gtag.js) --> <script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-8141015&amp;cx=c&amp;gtm=4e6a61"></script><script type="text/javascript" async="" src="//siteimproveanalytics.com/js/siteanalyze_6044943.js"></script><script src="https://connect.facebook.net/signals/config/1290758077759811?v=2.9.415&amp;r=stable&amp;domain=www.purdue.edu&amp;hme=a4c28c8787325ac3f8f9eac68364f47df2a8c4266e43177443e5d7f6289c9774&amp;ex_m=117%2C240%2C170%2C27%2C81%2C82%2C161%2C77%2C76%2C11%2C180%2C101%2C20%2C152%2C140%2C46%2C84%2C89%2C148%2C175%2C182%2C8%2C4%2C5%2C7%2C6%2C3%2C102%2C114%2C32%2C17%2C31%2C18%2C33%2C34%2C35%2C37%2C55%2C162%2C86%2C125%2C22%2C24%2C51%2C47%2C49%2C48%2C94%2C103%2C107%2C123%2C159%2C163%2C53%2C124%2C29%2C26%2C132%2C78%2C43%2C165%2C164%2C166%2C156%2C154%2C30%2C42%2C66%2C122%2C177%2C79%2C21%2C127%2C92%2C75%2C23%2C96%2C97%2C129%2C95%2C150%2C149%2C153%2C108%2C176%2C179%2C41%2C56%2C126%2C54%2C160%2C71%2C184%2C109%2C183%2C209%2C254%2C83%2C273%2C272%2C271%2C14%2C25%2C28%2C40%2C62%2C116%2C68%2C10%2C72%2C110%2C111%2C112%2C118%2C143%2C38%2C36%2C145%2C146%2C147%2C142%2C141%2C171%2C85%2C174%2C172%2C173%2C57%2C67%2C136%2C19%2C178%2C52%2C322%2C323%2C324%2C321%2C337%2C359%2C247%2C236%2C69%2C237%2C235%2C362%2C353%2C59%2C248%2C120%2C144%2C91%2C134%2C61%2C133%2C139%2C138%2C65%2C73%2C167%2C87%2C88%2C128%2C44%2C39%2C60%2C63%2C113%2C181%2C1%2C137%2C16%2C135%2C12%2C2%2C64%2C104%2C15%2C74%2C70%2C131%2C100%2C99%2C186%2C187%2C105%2C106%2C9%2C115%2C185%2C58%2C157%2C98%2C90%2C80%2C130%2C119%2C168%2C50%2C158%2C0%2C93%2C151%2C155%2C169%2C45%2C121%2C13%2C188" async=""></script><script as

In [3]:
print(driver.find_element(By.TAG_NAME, "body").text)

Find Info For
Apply
News
President
Shop
Visit
Give
Emergency
Recreation & Wellness
MENU
Are you trying to find information for Purdue in Indianapolis? Visit our Purdue in Indianapolis webpage for more information.
Facility Usage
Facility Usage
Faculty/Staff Workout Area
Capacity: 4/25 // 16%
Last Updated: Oct-07 04:53pm
Upper Track (4th Floor)
Capacity: 1/10 // 10%
Last Updated: Oct-07 04:53pm
Upper Gym
Capacity: 6/100 // 6%
Last Updated: Oct-07 04:53pm
MP6
Capacity: 5/45 // 12%
Last Updated: Oct-07 04:53pm
MP7
Capacity: 0/45 // 0%
Last Updated: Oct-07 04:53pm
Upper Fitness
Capacity: 12/46 // 27%
Last Updated: Oct-07 04:53pm
MAC Court
Capacity: 12/100 // 12%
Last Updated: Oct-07 04:53pm
East Mezzanine (3rd Floor)
Capacity: 6/15 // 40%
Last Updated: Oct-07 04:53pm
Atrium Track (3rd Floor)
Capacity: 0/50 // 0%
Last Updated: Oct-07 04:53pm
West Mezzanine (3rd Floor)
Capacity: 4/25 // 16%
Last Updated: Oct-07 04:53pm
Mindfulness Room
Capacity: 1/20 // 5%
Last Updated: Oct-07 04:53pm
Racquetball Courts 9-16
Capacity: 0/80 // 0%
Last Updated: Oct-07 04:53pm
MP5
Capacity: 18/106 // 17%
Last Updated: Oct-07 04:53pm
Fitness Pavilion
Capacity: 23/70 // 33%
Last Updated: Oct-07 04:53pm
Fitness Loft
Capacity: 10/55 // 19%
Last Updated: Oct-07 04:53pm
Feature Gym
Capacity: 3/50 // 6%
Last Updated: Oct-07 04:53pm
B&G Gym 1-3
Capacity: 15/100 // 15%
Last Updated: Oct-07 04:53pm
B&G Gym 4-6
Capacity: 11/100 // 11%
Last Updated: Oct-07 04:53pm
Scifres
Capacity: 29/80 // 37%
Last Updated: Oct-07 04:53pm
MP2
Capacity: 0/100 // 0%
Last Updated: Oct-07 04:53pm
Climbing Wall
Closed Now
Bouldering Wall
Capacity: 7/26 // 27%
Last Updated: Oct-07 04:53pm
Kilter Board Wall
Capacity: 4/20 // 20%
Last Updated: Oct-07 04:53pm
East Fitness
Capacity: 26/208 // 13%
Last Updated: Oct-07 04:54pm
Olympic Lifting Room
Capacity: 2/16 // 13%
Last Updated: Oct-07 04:54pm
Racquetball Courts 2-3
Capacity: 5/20 // 25%
Last Updated: Oct-07 04:54pm
Climbing Cave
Capacity: 0/15 // 0%
Last Updated: Oct-07 04:54pm
Combative Arts Room
Capacity: 3/11 // 28%
Last Updated: Oct-07 04:54pm
MP3
Capacity: 4/20 // 20%
Last Updated: Oct-07 04:54pm
MP4
Capacity: 1/26 // 4%
Last Updated: Oct-07 04:54pm
Cycling Studio
Closed Now
APGL
Closed Now
Colby Fitness
Capacity: 53/380 // 14%
Last Updated: Oct-07 04:54pm
Lower Gym
Capacity: 68/282 // 25%
Last Updated: Oct-07 04:54pm
TREC
Closed Now
Outdoor Tennis
Capacity: 0/50 // 0%
Last Updated: Oct-07 04:54pm
Outdoor Pickleball
Capacity: 26/50 // 52%
Last Updated: Oct-07 04:54pm

Last modified: July 1, 2020
Resources
EXPLORE
Campus Map
Careers
Center for Healthy Living
Colleges and Schools
Directory
Entrepreneurship and Commercialization
Human Resources
Libraries
INFORMATION
Ethics and Compliance
Events
Give
Lost and Found
Office of Engagement
President
Tuition Calculator
RESOURCES
BoilerConnect
Brightspace
Current Students
Faculty and Staff
myPurdue
Office 365
OneCampus Portal
Outlook
COMMUNICATION
Annual Security Report
Construction
Emergency
Information Technology
Marketing and Communications
Purdue News
Purdue Hotline
Timely Warnings
Facebook
Twitter
YouTube
Instagram
LinkedIn
Copyright © 2026 Purdue University. All Rights Reserved.
Accessibility | EA/EO University | Integrity Statement | Privacy Policy

In [6]:
#extracting individual facilities 
body_text = driver.find_element(By.TAG_NAME, "body").text

print(body_text)

lines = body_text.splitlines()

for line in lines:
    if "Capacity:" in line:
        print(line)

Find Info For
Apply
News
President
Shop
Visit
Give
Emergency
Recreation & Wellness
MENU
Are you trying to find information for Purdue in Indianapolis? Visit our Purdue in Indianapolis webpage for more information.
Facility Usage
Facility Usage
Faculty/Staff Workout Area
Capacity: 4/25 // 16%
Last Updated: Oct-07 04:53pm
Upper Track (4th Floor)
Capacity: 1/10 // 10%
Last Updated: Oct-07 04:53pm
Upper Gym
Capacity: 6/100 // 6%
Last Updated: Oct-07 04:53pm
MP6
Capacity: 5/45 // 12%
Last Updated: Oct-07 04:53pm
MP7
Capacity: 0/45 // 0%
Last Updated: Oct-07 04:53pm
Upper Fitness
Capacity: 12/46 // 27%
Last Updated: Oct-07 04:53pm
MAC Court
Capacity: 12/100 // 12%
Last Updated: Oct-07 04:53pm
East Mezzanine (3rd Floor)
Capacity: 6/15 // 40%
Last Updated: Oct-07 04:53pm
Atrium Track (3rd Floor)
Capacity: 0/50 // 0%
Last Updated: Oct-07 04:53pm
West Mezzanine (3rd Floor)
Capacity: 4/25 // 16%
Last Updated: Oct-07 04:53pm
Mindfulness Room
Capacity: 1/20 // 5%
Last Updated: Oct-07 04:53pm
Racquetball Courts 9-16
Capacity: 0/80 // 0%
Last Updated: Oct-07 04:53pm
MP5
Capacity: 18/106 // 17%
Last Updated: Oct-07 04:53pm
Fitness Pavilion
Capacity: 23/70 // 33%
Last Updated: Oct-07 04:53pm
Fitness Loft
Capacity: 10/55 // 19%
Last Updated: Oct-07 04:53pm
Feature Gym
Capacity: 3/50 // 6%
Last Updated: Oct-07 04:53pm
B&G Gym 1-3
Capacity: 15/100 // 15%
Last Updated: Oct-07 04:53pm
B&G Gym 4-6
Capacity: 11/100 // 11%
Last Updated: Oct-07 04:53pm
Scifres
Capacity: 29/80 // 37%
Last Updated: Oct-07 04:53pm
MP2
Capacity: 0/100 // 0%
Last Updated: Oct-07 04:53pm
Climbing Wall
Closed Now
Bouldering Wall
Capacity: 7/26 // 27%
Last Updated: Oct-07 04:53pm
Kilter Board Wall
Capacity: 4/20 // 20%
Last Updated: Oct-07 04:53pm
East Fitness
Capacity: 26/208 // 13%
Last Updated: Oct-07 04:54pm
Olympic Lifting Room
Capacity: 2/16 // 13%
Last Updated: Oct-07 04:54pm
Racquetball Courts 2-3
Capacity: 5/20 // 25%
Last Updated: Oct-07 04:54pm
Climbing Cave
Capacity: 0/15 // 0%
Last Updated: Oct-07 04:54pm
Combative Arts Room
Capacity: 3/11 // 28%
Last Updated: Oct-07 04:54pm
MP3
Capacity: 4/20 // 20%
Last Updated: Oct-07 04:54pm
MP4
Capacity: 1/26 // 4%
Last Updated: Oct-07 04:54pm
Cycling Studio
Closed Now
APGL
Closed Now
Colby Fitness
Capacity: 53/380 // 14%
Last Updated: Oct-07 04:54pm
Lower Gym
Capacity: 68/282 // 25%
Last Updated: Oct-07 04:54pm
TREC
Closed Now
Outdoor Tennis
Capacity: 0/50 // 0%
Last Updated: Oct-07 04:54pm
Outdoor Pickleball
Capacity: 26/50 // 52%
Last Updated: Oct-07 04:54pm

Last modified: July 1, 2020
Resources
EXPLORE
Campus Map
Careers
Center for Healthy Living
Colleges and Schools
Directory
Entrepreneurship and Commercialization
Human Resources
Libraries
INFORMATION
Ethics and Compliance
Events
Give
Lost and Found
Office of Engagement
President
Tuition Calculator
RESOURCES
BoilerConnect
Brightspace
Current Students
Faculty and Staff
myPurdue
Office 365
OneCampus Portal
Outlook
COMMUNICATION
Annual Security Report
Construction
Emergency
Information Technology
Marketing and Communications
Purdue News
Purdue Hotline
Timely Warnings
Facebook
Twitter
YouTube
Instagram
LinkedIn
Copyright © 2026 Purdue University. All Rights Reserved.
Accessibility | EA/EO University | Integrity Statement | Privacy Policy
Capacity: 4/25 // 16%
Capacity: 1/10 // 10%
Capacity: 6/100 // 6%
Capacity: 5/45 // 12%
Capacity: 0/45 // 0%
Capacity: 12/46 // 27%
Capacity: 12/100 // 12%
Capacity: 6/15 // 40%
Capacity: 0/50 // 0%
Capacity: 4/25 // 16%
Capacity: 1/20 // 5%
Capacity: 0/80 // 0%
Capacity: 18/106 // 17%
Capacity: 23/70 // 33%
Capacity: 10/55 // 19%
Capacity: 3/50 // 6%
Capacity: 15/100 // 15%
Capacity: 11/100 // 11%
Capacity: 29/80 // 37%
Capacity: 0/100 // 0%
Capacity: 7/26 // 27%
Capacity: 4/20 // 20%
Capacity: 26/208 // 13%
Capacity: 2/16 // 13%
Capacity: 5/20 // 25%
Capacity: 0/15 // 0%
Capacity: 3/11 // 28%
Capacity: 4/20 // 20%
Capacity: 1/26 // 4%
Capacity: 53/380 // 14%
Capacity: 68/282 // 25%
Capacity: 0/50 // 0%
Capacity: 26/50 // 52%

In [7]:
#parse those numbers: 
import re

for line in lines:
    if "Capacity:" in line:

        match = re.search(
            r"Capacity:\s*(\d+)/(\d+)\s*//\s*(\d+)%",
            line
        )

        if match:

            current = int(match.group(1))
            capacity = int(match.group(2))
            percent = int(match.group(3))

            print(current, capacity, percent)

4 25 16
1 10 10
6 100 6
5 45 12
0 45 0
12 46 27
12 100 12
6 15 40
0 50 0
4 25 16
1 20 5
0 80 0
18 106 17
23 70 33
10 55 19
3 50 6
15 100 15
11 100 11
29 80 37
0 100 0
7 26 27
4 20 20
26 208 13
2 16 13
5 20 25
0 15 0
3 11 28
4 20 20
1 26 4
53 380 14
68 282 25
0 50 0
26 50 52

In [8]:
#inspect the rendered HTML structure:
from bs4 import BeautifulSoup

html = driver.page_source
soup = BeautifulSoup(html, "html.parser")

print(soup.prettify()[:10000])

<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Facility Usage | Purdue University
  </title>
  <link href="https://www.purdue.edu/recwell/facility-usage/index.php" rel="canonical"/>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,initial-scale=1" name="viewport"/>
  <!-- Google tag (gtag.js) -->
  <script async="" src="https://www.googletagmanager.com/gtag/destination?id=DC-8141015&amp;cx=c&amp;gtm=4e6a60" type="text/javascript">
  </script>
  <script async="" src="//siteimproveanalytics.com/js/siteanalyze_6044943.js" type="text/javascript">
  </script>
  <script async="" src="https://connect.facebook.net/signals/config/1290758077759811?v=2.9.415&amp;r=stable&amp;domain=www.purdue.edu&amp;hme=a4c28c8787325ac3f8f9eac68364f47df2a8c4266e43177443e5d7f6289c9774&amp;ex_m=117%2C240%2C170%2C27%2C81%2C82%2C161%2C77%2C76%2C11%2C180%2C101%2C20%2C152%2C140%2C46%2C84%2C89%2C148%2C175%2C182%2C8%2C4%2C5%2C7%2C6%2C3%2C102%2C114%2C32%2C17%2C31%2C18%2C33%2C34%2C35%2C37%2C55%2C162%2C86%2C125%2C22%2C24%2C51%2C47%2C49%2C48%2C94%2C103%2C107%2C123%2C159%2C163%2C53%2C124%2C29%2C26%2C132%2C78%2C43%2C165%2C164%2C166%2C156%2C154%2C30%2C42%2C66%2C122%2C177%2C79%2C21%2C127%2C92%2C75%2C23%2C96%2C97%2C129%2C95%2C150%2C149%2C153%2C108%2C176%2C179%2C41%2C56%2C126%2C54%2C160%2C71%2C184%2C109%2C183%2C209%2C254%2C83%2C273%2C272%2C271%2C14%2C25%2C28%2C40%2C62%2C116%2C68%2C10%2C72%2C110%2C111%2C112%2C118%2C143%2C38%2C36%2C145%2C146%2C147%2C142%2C141%2C171%2C85%2C174%2C172%2C173%2C57%2C67%2C136%2C19%2C178%2C52%2C322%2C323%2C324%2C321%2C337%2C359%2C247%2C236%2C69%2C237%2C235%2C362%2C353%2C59%2C248%2C120%2C144%2C91%2C134%2C61%2C133%2C139%2C138%2C65%2C73%2C167%2C87%2C88%2C128%2C44%2C39%2C60%2C63%2C113%2C181%2C1%2C137%2C16%2C135%2C12%2C2%2C64%2C104%2C15%2C74%2C70%2C131%2C100%2C99%2C186%2C187%2C105%2C106%2C9%2C115%2C185%2C58%2C157%2C98%2C90%2C80%2C130%2C119%2C168%2C50%2C158%2C0%2C93%2C151%2C155%2C169%2C45%2C121%2C13%2C188">
  </script>
  <script async="" src="https://connect.facebook.net/en_US/fbevents.js">
  </script>
  <script async="" src="https://s.yimg.com/wi/ytc.js">
  </script>
  <script async="" src="https://static.ads-twitter.com/uwt.js" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-B26WBBQ27X&amp;cx=c&amp;gtm=4e6a60" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-PF1CYQ27F6&amp;cx=c&amp;gtm=4e6a60" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-WWGMN6Z">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-T85DGJNVF8">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-T85DGJNVF8');
  </script>
  <!-- Google Tag Manager -->
  <script>
   // <![CDATA[
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WWGMN6Z');
// ]]>
  </script>
  <!-- End Google Tag Manager -->
  <link href="https://www.purdue.edu/purdue/images/favicon.ico" rel="shortcut icon"/>
  <link href="https://www.purdue.edu/purdue/images/icon-iphone.png" rel="apple-touch-icon" sizes="76x76"/>
  <link href="https://www.purdue.edu/purdue/images/icon-ipad.png" rel="apple-touch-icon" sizes="76x76"/>
  <link href="https://www.purdue.edu/purdue/images/icon-iphone-retina.png" rel="apple-touch-icon" sizes="120x120"/>
  <link href="https://www.purdue.edu/purdue/images/icon-ipad-retina.png" rel="apple-touch-icon" sizes="152x152"/>
  <meta content="#c28e0e" name="msapplication-TileColor"/>
  <meta content="#ffffff" name="theme-color"/>
  <!--United sans -->
  <link href="https://www.purdue.edu/purdue/fonts/united-sans/united-sans.css" rel="stylesheet"/>
  <!-- Acumin Pro -->
  <link href="https://use.typekit.net/kyp3nae.css" rel="stylesheet"/>
  <link href="/recwell/assets/css/templates/default.css" rel="stylesheet"/>
  <style type="text/css">
   .content__main h2:first-of-type {
        margin-top: 0;
    }
  </style>
  <script src="https://www.google.com/cse/static/element/3735a6ee3000c0cb/cse_element__en.js?usqp=CAI%3D" type="text/javascript">
  </script>
  <link href="https://www.google.com/cse/static/element/3735a6ee3000c0cb/default_v6+en.css" rel="stylesheet" type="text/css"/>
  <link href="https://www.google.com/cse/static/style/look/v6/minimalist.css" rel="stylesheet" type="text/css"/>
  <style type="text/css">
   .gsc-control-cse{font-family:arial, sans-serif}.gsc-control-cse .gsc-table-result{font-family:arial, sans-serif}.gsc-refinementsGradient{background:linear-gradient(to left,rgba(255,255,255,1),rgba(255,255,255,0))}.gsc-control-cse{border-color:#FFFFFF;background-color:#FFFFFF}.gsc-results-wrapper-overlay{background-color:#FFFFFF}input.gsc-input,.gsc-input-box,.gsc-input-box-hover,.gsc-input-box-focus{border-color:#BBBBBB}.gsc-search-button-v2,.gsc-search-button-v2:hover,.gsc-search-button-v2:focus{border-color:#CFB991;background-color:#CFB991;background-image:none;filter:none}.gsc-search-button-v2 svg{fill:#000000}.gsc-tabHeader.gsc-tabhActive,.gsc-refinementHeader.gsc-refinementhActive{color:#444444;border-color:#444444;background-color:#FFFFFF}.gsc-tabHeader.gsc-tabhInactive,.gsc-refinementHeader.gsc-refinementhInactive{color:#333333;border-color:#333333;background-color:#FFFFFF}.gsc-webResult.gsc-result,.gsc-results .gsc-imageResult{border-color:#FFFFFF;background-color:#FFFFFF}.gsc-webResult.gsc-result:hover{border-color:#000000;background-color:#FFFFFF}.gs-webResult.gs-result a.gs-title:link,.gs-webResult.gs-result a.gs-title:link b,.gs-imageResult a.gs-title:link,.gs-imageResult a.gs-title:link b{color:#444444}.gs-webResult.gs-result a.gs-title:visited,.gs-webResult.gs-result a.gs-title:visited b,.gs-imageResult a.gs-title:visited,.gs-imageResult a.gs-title:visited b{color:#444444}.gs-webResult.gs-result a.gs-title:hover,.gs-webResult.gs-result a.gs-title:hover b,.gs-imageResult a.gs-title:hover,.gs-imageResult a.gs-title:hover b{color:#444444}.gs-webResult.gs-result a.gs-title:active,.gs-webResult.gs-result a.gs-title:active b,.gs-imageResult a.gs-title:active,.gs-imageResult a.gs-title:active b{color:#777777}.gsc-cursor-page{color:#444444}a.gsc-trailing-more-results:link{color:#444444}.gs-webResult:not(.gs-no-results-result):not(.gs-error-result) .gs-snippet,.gs-fileFormatType{color:#333333}.gs-webResult div.gs-visibleUrl{color:#000000}.gs-webResult div.gs-visibleUrl-short{color:#000000}.gsc-cursor-box{border-color:#FFFFFF}.gsc-results .gsc-cursor-box .gsc-cursor-page{border-color:#333333;background-color:#FFFFFF;color:#333333}.gsc-results .gsc-cursor-box .gsc-cursor-current-page{border-color:#444444;background-color:#FFFFFF;color:#444444}.gsc-webResult.gsc-result.gsc-promotion{border-color:#CCCCCC;background-color:#E6E6E6}.gsc-completion-container{border-color:#BBBBBB}.gsc-completion-title{color:#444444}.gsc-completion-snippet{color:#333333}.gs-promotion a.gs-title:link,.gs-promotion a.gs-title:link *,.gs-promotion .gs-snippet a:link{color:#0000CC}.gs-promotion a.gs-title:visited,.gs-promotion a.gs-title:visited *,.gs-promotion .gs-snippet a:visited{color:#0000CC}.gs-promotion a.gs-title:hover,.gs-promotion a.gs-title:hover *,.gs-promotion .gs-snippet a:hover{color:#444444}.gs-promotion a.gs-title:active,.gs-promotion a.gs-title:active *,.gs-promotion .gs-snippet a:active{color:#00CC00}.gs-promotion .gs-snippet,.gs-promotion .gs-title .gs-promotion-title-right,.gs-promotion .gs-title .gs-promotion-title-right *{color:#333333}.gs-promotion .gs-visibleUrl,.gs-promotion .gs-visibleUrl-short{color:#00CC00}.gcsc-find-more-on-google{color:#444444}.gcsc-find-more-on-google-magnifier{fill:#444444}
  </style>
  <style type="text/css">
   .gscb_a{display:inline-block;font:27px/13px arial,sans-serif}.gsst_a .gscb_a{color:#a1b9ed;cursor:pointer}.gsst_a:hover .gscb_a,.gsst_a:focus .gscb_a{color:#36c}.gsst_a{display:inline-block}.gsst_a{cursor:pointer;padding:0 4px}.gsst_a:hover{text-decoration:none!important}.gsst_b{font-size:16px;padding:0 2px;position:relative;user-select:none;-webkit-user-select:none;white-space:nowrap}.gsst_e{vertical-align:middle;opacity:0.55;}.gsst_a:hover .gsst_e,.gsst_a:focus .gsst_e{opacity:0.72;}.gsst_a:active .gsst_e{opacity:1;}.gsst_f{background:white;text-align:left}.gsst_g{background-color:white;border:1px solid #ccc;border-top-color:#d9d9d9;box-shadow:0 2px 4px rgba(0,0,0,0.2);-webkit-box-shadow:0 2px 4px rgba(0,0,0,0.2);margin:-1px -3px;padding:0 6px}.gsst_h{background-color:white;height:1px;margin-bottom:-1px;position:relative;top:-1px}.gsib_a{width:100%;padding:4px 6px 0}.gsib_a,.gsib_b{vertical-align:top}.gssb_c{border:0;position:absolute;z-index:989}.gssb_e{border:1px solid #ccc;border-top-color:#d9d9d9;box-shadow:0 2px 4px rgba(0,0,0,0.2);-webkit-box-shadow:0 2px 4px rgba(0,0,0,0.2);cursor:default}.gssb_f{visibility:hidden;white-space:nowrap}.gssb_k{border:0;display:block;position:absolute;top:0;z-index:988}.gsdd_a{border:none!important}.gsq_a{padding:0}.gssb_a{padding:0 7px}.gssb_a,.gssb_a td{white-space:nowrap;overflow:hidden;line-height:22px}#gssb_b{font-size:11px;color:#36c;text-decoration:none}#gssb_b:hover{font-size:11px;color:#36c;text-decoration:underline}.gssb_g{text-align:center;padding:8px 0 7px;position:relative}.gssb_h{font-size:15px;height:28px;margin:0.2em;-webkit-appearance:button}.gssb_i{background:#eee}.gss_ifl{visibility:hidden;padding-left:5px}.gssb_i .gss_ifl{visibility:visible}a.gssb_j{font-size:13px;color:#36c;text-decoration:none;line-height:100%}a.gssb_j:hover{text-decoration:underline}.gssb_l{height:1px;background-color:#e5e5e5}.g

In [9]:
text = soup.find(string=lambda x: x and "Upper Fitness" in x)

print(text)
print(text.parent)

Upper Fitness
<h5 class="rw-c2c-feed__location--name">Upper Fitness </h5>

In [10]:
print(text.parent.parent)

<div class="rw-c2c-feed__location"><h5 class="rw-c2c-feed__location--name">Upper Fitness </h5><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="27" class="MuiLinearProgress-root MuiLinearProgress-colorPrimary rw-c2c-feed__location--progress MuiLinearProgress-determinate" role="progressbar"><div class="MuiLinearProgress-bar MuiLinearProgress-barColorPrimary MuiLinearProgress-bar1Determinate" style="transform: translateX(-73%);"></div></div><div class="rw-c2c-feed__location--about"><span class="rw-c2c-feed__about--capacity">Capacity: 12/46 // 27%</span><span class="rw-c2c-feed__about--update">Last Updated: Oct-07 04:53pm</span></div></div>

In [11]:
#finding number of facilities -- checking if it works 
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

url = "https://www.purdue.edu/recwell/facility-usage/index.php"

#Open Chrome
driver = webdriver.Chrome()

#Open Purdue facility usage page
driver.get(url)

#Wait for JavaScript to load the facility data
time.sleep(5)

#Get the fully rendered HTML
html = driver.page_source

#Parse the HTML
soup = BeautifulSoup(html, "html.parser")

#Find every facility
facility_cards = soup.find_all("div", class_="rw-c2c-feed__location")

print("Facilities found:", len(facility_cards))

Facilities found: 37

In [13]:
#scraping each facility:
facilities = []

for card in facility_cards:

    #Find the pieces inside each facility card
    name_tag = card.find(
        "h5",
        class_="rw-c2c-feed__location--name"
    )

    capacity_tag = card.find(
        "span",
        class_="rw-c2c-feed__about--capacity"
    )

    updated_tag = card.find(
        "span",
        class_="rw-c2c-feed__about--update"
    )

    #Skip cards that don't have the information we need
    if name_tag is None or capacity_tag is None:
        continue

    #Extract the text
    name = name_tag.get_text(strip=True)
    capacity_text = capacity_tag.get_text(strip=True)

    #Some cards may not have an update time
    if updated_tag is not None:
        updated = updated_tag.get_text(strip=True)
    else:
        updated = ""

    #Extract current people, capacity, and percentage
    match = re.search(
        r"Capacity:\s*(\d+)/(\d+)\s*//\s*(\d+)%",
        capacity_text
    )

    if match:

        current = int(match.group(1))
        capacity = int(match.group(2))
        percent = int(match.group(3))

        facilities.append({
            "timestamp": datetime.now(),
            "facility": name,
            "current": current,
            "capacity": capacity,
            "percent": percent,
            "last_updated": updated.replace("Last Updated:", "").strip()
        })

In [16]:
df = pd.DataFrame(facilities)

df

,timestamp,facility,current,capacity,percent,last_updated
0,2026-10-07 17:38:28.048160,Faculty/Staff Workout Area,5,25,20,Oct-07 05:25pm
1,2026-10-07 17:38:28.048266,Upper Track (4th Floor),1,10,10,Oct-07 05:25pm
2,2026-10-07 17:38:28.048340,Upper Gym,11,100,11,Oct-07 05:25pm
3,2026-10-07 17:38:28.048412,MP6,0,45,0,Oct-07 05:25pm
4,2026-10-07 17:38:28.048486,MP7,0,45,0,Oct-07 05:25pm
5,2026-10-07 17:38:28.048559,Upper Fitness,23,46,50,Oct-07 05:25pm
6,2026-10-07 17:38:28.048629,MAC Court,18,100,18,Oct-07 05:25pm
7,2026-10-07 17:38:28.048691,East Mezzanine (3rd Floor),5,15,34,Oct-07 05:25pm
8,2026-10-07 17:38:28.048756,Atrium Track (3rd Floor),2,50,4,Oct-07 05:25pm
9,2026-10-07 17:38:28.048820,West Mezzanine (3rd Floor),7,25,29,Oct-07 05:25pm
10,2026-10-07 17:38:28.048881,Mindfulness Room,3,20,15,Oct-07 05:25pm
11,2026-10-07 17:38:28.048943,Racquetball Courts 9-16,2,80,3,Oct-07 05:25pm
12,2026-10-07 17:38:28.049005,MP5,32,106,31,Oct-07 05:25pm
13,2026-10-07 17:38:28.049066,Fitness Pavilion,23,70,33,Oct-07 05:25pm
14,2026-10-07 17:38:28.049126,Fitness Loft,21,55,39,Oct-07 05:25pm
15,2026-10-07 17:38:28.049186,Feature Gym,2,50,4,Oct-07 05:25pm
16,2026-10-07 17:38:28.049248,B&G Gym 1-3,16,100,16,Oct-07 05:25pm
17,2026-10-07 17:38:28.049819,B&G Gym 4-6,33,100,33,Oct-07 05:25pm
18,2026-10-07 17:38:28.049884,Scifres,26,80,33,Oct-07 05:25pm
19,2026-10-07 17:38:28.049948,MP2,3,100,3,Oct-07 05:25pm
20,2026-10-07 17:38:28.050011,Climbing Wall,7,18,39,Oct-07 05:25pm
21,2026-10-07 17:38:28.050076,Bouldering Wall,15,26,58,Oct-07 05:25pm
22,2026-10-07 17:38:28.050139,Kilter Board Wall,1,20,5,Oct-07 05:25pm
23,2026-10-07 17:38:28.050202,East Fitness,21,208,11,Oct-07 05:25pm
24,2026-10-07 17:38:28.050270,Olympic Lifting Room,0,16,0,Oct-07 05:25pm
25,2026-10-07 17:38:28.050332,Racquetball Courts 2-3,3,20,15,Oct-07 05:25pm
26,2026-10-07 17:38:28.050392,Climbing Cave,0,15,0,Oct-07 05:26pm
27,2026-10-07 17:38:28.050449,Combative Arts Room,1,11,10,Oct-07 05:26pm
28,2026-10-07 17:38:28.050509,MP3,3,20,15,Oct-07 05:26pm
29,2026-10-07 17:38:28.050566,MP4,24,26,93,Oct-07 05:26pm
30,2026-10-07 17:38:28.050689,APGL,5,30,17,Oct-07 05:26pm
31,2026-10-07 17:38:28.050756,Colby Fitness,63,380,17,Oct-07 05:26pm
32,2026-10-07 17:38:28.050817,Lower Gym,71,282,26,Oct-07 05:26pm
33,2026-10-07 17:38:28.050925,Outdoor Tennis,4,50,8,Oct-07 05:26pm
34,2026-10-07 17:38:28.050992,Outdoor Pickleball,34,50,68,Oct-07 05:26pm

In [16]:
df = pd.DataFrame(facilities)

df

,timestamp,facility,current,capacity,percent,last_updated
0,2026-10-07 17:38:28.048160,Faculty/Staff Workout Area,5,25,20,Oct-07 05:25pm
1,2026-10-07 17:38:28.048266,Upper Track (4th Floor),1,10,10,Oct-07 05:25pm
2,2026-10-07 17:38:28.048340,Upper Gym,11,100,11,Oct-07 05:25pm
3,2026-10-07 17:38:28.048412,MP6,0,45,0,Oct-07 05:25pm
4,2026-10-07 17:38:28.048486,MP7,0,45,0,Oct-07 05:25pm
5,2026-10-07 17:38:28.048559,Upper Fitness,23,46,50,Oct-07 05:25pm
6,2026-10-07 17:38:28.048629,MAC Court,18,100,18,Oct-07 05:25pm
7,2026-10-07 17:38:28.048691,East Mezzanine (3rd Floor),5,15,34,Oct-07 05:25pm
8,2026-10-07 17:38:28.048756,Atrium Track (3rd Floor),2,50,4,Oct-07 05:25pm
9,2026-10-07 17:38:28.048820,West Mezzanine (3rd Floor),7,25,29,Oct-07 05:25pm
10,2026-10-07 17:38:28.048881,Mindfulness Room,3,20,15,Oct-07 05:25pm
11,2026-10-07 17:38:28.048943,Racquetball Courts 9-16,2,80,3,Oct-07 05:25pm
12,2026-10-07 17:38:28.049005,MP5,32,106,31,Oct-07 05:25pm
13,2026-10-07 17:38:28.049066,Fitness Pavilion,23,70,33,Oct-07 05:25pm
14,2026-10-07 17:38:28.049126,Fitness Loft,21,55,39,Oct-07 05:25pm
15,2026-10-07 17:38:28.049186,Feature Gym,2,50,4,Oct-07 05:25pm
16,2026-10-07 17:38:28.049248,B&G Gym 1-3,16,100,16,Oct-07 05:25pm
17,2026-10-07 17:38:28.049819,B&G Gym 4-6,33,100,33,Oct-07 05:25pm
18,2026-10-07 17:38:28.049884,Scifres,26,80,33,Oct-07 05:25pm
19,2026-10-07 17:38:28.049948,MP2,3,100,3,Oct-07 05:25pm
20,2026-10-07 17:38:28.050011,Climbing Wall,7,18,39,Oct-07 05:25pm
21,2026-10-07 17:38:28.050076,Bouldering Wall,15,26,58,Oct-07 05:25pm
22,2026-10-07 17:38:28.050139,Kilter Board Wall,1,20,5,Oct-07 05:25pm
23,2026-10-07 17:38:28.050202,East Fitness,21,208,11,Oct-07 05:25pm
24,2026-10-07 17:38:28.050270,Olympic Lifting Room,0,16,0,Oct-07 05:25pm
25,2026-10-07 17:38:28.050332,Racquetball Courts 2-3,3,20,15,Oct-07 05:25pm
26,2026-10-07 17:38:28.050392,Climbing Cave,0,15,0,Oct-07 05:26pm
27,2026-10-07 17:38:28.050449,Combative Arts Room,1,11,10,Oct-07 05:26pm
28,2026-10-07 17:38:28.050509,MP3,3,20,15,Oct-07 05:26pm
29,2026-10-07 17:38:28.050566,MP4,24,26,93,Oct-07 05:26pm
30,2026-10-07 17:38:28.050689,APGL,5,30,17,Oct-07 05:26pm
31,2026-10-07 17:38:28.050756,Colby Fitness,63,380,17,Oct-07 05:26pm
32,2026-10-07 17:38:28.050817,Lower Gym,71,282,26,Oct-07 05:26pm
33,2026-10-07 17:38:28.050925,Outdoor Tennis,4,50,8,Oct-07 05:26pm
34,2026-10-07 17:38:28.050992,Outdoor Pickleball,34,50,68,Oct-07 05:26pm

In [26]:
def scrape_facilities():

    url = "https://www.purdue.edu/recwell/facility-usage/index.php"

    driver = webdriver.Chrome()
    driver.get(url)

    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located(
            (By.CLASS_NAME, "rw-c2c-feed__location")
        )
    )

    soup = BeautifulSoup(driver.page_source, "html.parser")

    facility_cards = soup.find_all(
        "div",
        class_="rw-c2c-feed__location"
    )

    facilities = []

    for card in facility_cards:

        name_tag = card.find(
            "h5",
            class_="rw-c2c-feed__location--name"
        )

        capacity_tag = card.find(
            "span",
            class_="rw-c2c-feed__about--capacity"
        )

        updated_tag = card.find(
            "span",
            class_="rw-c2c-feed__about--update"
        )

        if name_tag is None or capacity_tag is None:
            continue

        name = name_tag.get_text(strip=True)
        capacity_text = capacity_tag.get_text(strip=True)

        if updated_tag is not None:
            updated = updated_tag.get_text(strip=True)
        else:
            updated = ""

        match = re.search(
            r"Capacity:\s*(\d+)/(\d+)\s*//\s*(\d+)%",
            capacity_text
        )

        if match:

            facilities.append({
                "timestamp": datetime.now(),
                "facility": name,
                "current": int(match.group(1)),
                "capacity": int(match.group(2)),
                "percent": int(match.group(3)),
                "last_updated": updated.replace(
                    "Last Updated:", ""
                ).strip()
            })

    driver.quit()

    return pd.DataFrame(facilities)

In [28]:
df = scrape_facilities()
df

,timestamp,facility,current,capacity,percent,last_updated
0,2026-10-07 18:02:37.138787,Faculty/Staff Workout Area,5,25,20,Oct-07 05:25pm
1,2026-10-07 18:02:37.138849,Upper Track (4th Floor),1,10,10,Oct-07 05:25pm
2,2026-10-07 18:02:37.138883,Upper Gym,11,100,11,Oct-07 05:25pm
3,2026-10-07 18:02:37.138915,MP6,0,45,0,Oct-07 05:25pm
4,2026-10-07 18:02:37.138945,MP7,0,45,0,Oct-07 05:25pm
5,2026-10-07 18:02:37.138973,Upper Fitness,23,46,50,Oct-07 05:25pm
6,2026-10-07 18:02:37.139001,MAC Court,18,100,18,Oct-07 05:25pm
7,2026-10-07 18:02:37.139030,East Mezzanine (3rd Floor),5,15,34,Oct-07 05:25pm
8,2026-10-07 18:02:37.139059,Atrium Track (3rd Floor),2,50,4,Oct-07 05:25pm
9,2026-10-07 18:02:37.139087,West Mezzanine (3rd Floor),7,25,29,Oct-07 05:25pm
10,2026-10-07 18:02:37.139115,Mindfulness Room,3,20,15,Oct-07 05:25pm
11,2026-10-07 18:02:37.139143,Racquetball Courts 9-16,2,80,3,Oct-07 05:25pm
12,2026-10-07 18:02:37.139171,MP5,32,106,31,Oct-07 05:25pm
13,2026-10-07 18:02:37.139199,Fitness Pavilion,23,70,33,Oct-07 05:25pm
14,2026-10-07 18:02:37.139227,Fitness Loft,21,55,39,Oct-07 05:25pm
15,2026-10-07 18:02:37.139254,Feature Gym,2,50,4,Oct-07 05:25pm
16,2026-10-07 18:02:37.139281,B&G Gym 1-3,16,100,16,Oct-07 05:25pm
17,2026-10-07 18:02:37.139311,B&G Gym 4-6,33,100,33,Oct-07 05:25pm
18,2026-10-07 18:02:37.139337,Scifres,26,80,33,Oct-07 05:25pm
19,2026-10-07 18:02:37.139365,MP2,3,100,3,Oct-07 05:25pm
20,2026-10-07 18:02:37.139391,Climbing Wall,7,18,39,Oct-07 05:25pm
21,2026-10-07 18:02:37.139417,Bouldering Wall,15,26,58,Oct-07 05:25pm
22,2026-10-07 18:02:37.139444,Kilter Board Wall,1,20,5,Oct-07 05:25pm
23,2026-10-07 18:02:37.139470,East Fitness,21,208,11,Oct-07 05:25pm
24,2026-10-07 18:02:37.139497,Olympic Lifting Room,0,16,0,Oct-07 05:25pm
25,2026-10-07 18:02:37.139523,Racquetball Courts 2-3,3,20,15,Oct-07 05:25pm
26,2026-10-07 18:02:37.139550,Climbing Cave,0,15,0,Oct-07 05:26pm
27,2026-10-07 18:02:37.139576,Combative Arts Room,1,11,10,Oct-07 05:26pm
28,2026-10-07 18:02:37.139602,MP3,3,20,15,Oct-07 05:26pm
29,2026-10-07 18:02:37.139628,MP4,24,26,93,Oct-07 05:26pm
30,2026-10-07 18:02:37.139678,APGL,5,30,17,Oct-07 05:26pm
31,2026-10-07 18:02:37.139704,Colby Fitness,63,380,17,Oct-07 05:26pm
32,2026-10-07 18:02:37.139730,Lower Gym,71,282,26,Oct-07 05:26pm
33,2026-10-07 18:02:37.139777,Outdoor Tennis,4,50,8,Oct-07 05:26pm
34,2026-10-07 18:02:37.139804,Outdoor Pickleball,34,50,68,Oct-07 05:26pm

In [29]:
file_name = "crowdcast_data.csv"

df.to_csv(
    file_name,
    mode="a",
    header=not os.path.exists(file_name),
    index=False
)

print("Saved new facility data")

Saved new facility data

In [ ]:
#automatic collection

#every hour
import time
import os
from datetime import datetime

while True:

    df = scrape_facilities()

    df.to_csv(
        "crowdcast_data.csv",
        mode="a",
        header=not os.path.exists("crowdcast_data.csv"),
        index=False
    )

    print("Saved at:", datetime.now())

    #600 seconds = every 10 minutes 
    time.sleep(600)

In [32]:
import pandas as pd

data = pd.read_csv("crowdcast_data.csv")

data.tail(20)

,timestamp,facility,current,capacity,percent,last_updated
308,2026-10-07 19:28:06.702005,B&G Gym 4-6,36,100,36,Oct-07 07:23pm
309,2026-10-07 19:28:06.702034,Scifres,23,80,29,Oct-07 07:23pm
310,2026-10-07 19:28:06.702061,MP2,22,100,22,Oct-07 07:23pm
311,2026-10-07 19:28:06.702088,Climbing Wall,4,18,23,Oct-07 07:23pm
312,2026-10-07 19:28:06.702115,Bouldering Wall,23,26,89,Oct-07 07:23pm
313,2026-10-07 19:28:06.702143,Kilter Board Wall,0,20,0,Oct-07 07:23pm
314,2026-10-07 19:28:06.702171,East Fitness,21,208,11,Oct-07 07:23pm
315,2026-10-07 19:28:06.702199,Olympic Lifting Room,0,16,0,Oct-07 07:23pm
316,2026-10-07 19:28:06.702226,Racquetball Courts 2-3,0,20,0,Oct-07 07:23pm
317,2026-10-07 19:28:06.702253,Climbing Cave,0,15,0,Oct-07 07:23pm
318,2026-10-07 19:28:06.702280,Combative Arts Room,8,11,73,Oct-07 07:23pm
319,2026-10-07 19:28:06.702307,MP3,16,20,80,Oct-07 07:23pm
320,2026-10-07 19:28:06.702334,MP4,8,26,31,Oct-07 07:23pm
321,2026-10-07 19:28:06.702360,Cycling Studio,14,60,24,Oct-07 07:23pm
322,2026-10-07 19:28:06.702386,APGL,9,30,30,Oct-07 07:23pm
323,2026-10-07 19:28:06.702412,Colby Fitness,72,380,19,Oct-07 07:23pm
324,2026-10-07 19:28:06.702439,Lower Gym,69,282,25,Oct-07 07:23pm
325,2026-10-07 19:28:06.702465,TREC,41,300,14,Oct-07 07:02pm
326,2026-10-07 19:28:06.702493,Outdoor Tennis,4,50,8,Oct-07 07:02pm
327,2026-10-07 19:28:06.702521,Outdoor Pickleball,60,50,120,Oct-07 07:02pm

In [33]:
import os
print(os.getcwd())

/Users/nikki/CrowdCast